sudo: false
dist: trusty
language: node_js
node_js:
- '4.1'
script:
- make
after_script:
- test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test
  $TRAVIS_BRANCH == "master" && make install
env:
  global:
    secure: CDEuBhb4Y1WMKkQ9+d4uH36UnJQGfF3LnTshAaPDhrEJMJnYGD0FmKv/cPPqbM25/Z9vM+ZzWyNnoEskwdQOrV5jiE5lbRUFvMIKVMgHWuOZUmR+vuZXKIZ3PGx56/BC5AOgur7PESpqYDuQ7beN7s4BCFziiXInIOPhU/gfjN2rPQ1IFxqHY4LT6PQ81wUWlnH6/7BRLL4aIN7+BIy75rDvdQvKVOucFXcwJKostK44/ReSPzSqtt9pDJGLNx6/J7waG29erkWQTf0WDkt4el+Z15/Q2v9aRyS5fWOV7Zm3SJE1aoszOXCoH0iXbHUADwfKL98uhp2GtKQBNs3Q5RROshdmh3GhIhRkr8fq0LF3U1lW8OMDFBWcThdpgE2fJ19mspM1Z05GRepeOxAhBNpzp7XoGMqNSIWh3z634yKIZxoLa20hmfMLLyUriipCDiKtXBBxbz2DCCj8yWCxzNqMyDZvdZBzPt7x6JCoaozGGz+eR8YR/fuqEsAuMI6rXmkOruiy6A9w454X3rL4SIjEah77rHPOPaL5aHgvsTuc1ZTWTqCha3099vE8GW75rw9vuGyac45ToukQ3akgVcXeoR5RIrHPiAh+7po2YQeTjx5LVxCMhdSSwFtXGQ12ywzWjOykCO5DT4ft4Lqwh4miaDIhZw3Ezz/WnH77MSE=
notifications:
  slack:
    secure: ylZJxfbuEvyytuJ1LL/tRJ3QXK8dMCJjJVrZCnaI6S8kjquMY8E7rykjUKX7xl7BDzgz9DopO5+7u1xc6H5EVSHl0rMOCJL9eXmmHFxyX1G0O35efRpW3ObXkPov97IV622mZojKRITMNEoD6xn7v4+vV90baA57ssUm2Wu+XbdLiCYKXLIf9r050rarJmu3/E60hjzS/3zjsuOajCOUcMRwW65nwmZQ//H8foFFFHVvblJLks2RKzCVXCcwNtyk/hW2X81Way26FxIMx//xp6kV5NEzyNhq3ll4cs42ekv/lt57XYzKCwJiaCJjr1+AZg3qdBvPid2B0OWh2Q64UOm1yhKQAibqJ0ThfQ2iJeO/ZE8tlqq1xe/lMA7xXw7Qo4rmgdVDHj/nuH77pI+/ETUaewURZxiqVO/CumWBL83M+HbKXSpUohe33v/BtS62sh1Z5JRlNuuAZZgkRrAQT1e1SE2dycXR1EMv3FfI6DegmWOGQKCQTISWIc8FPx8O/DN5v0xpqCgTfNgzn4PeZpEPPx8hPgfVu/uGbPtOoTzwFmHd4/8Caxw/IsmOt5m0Cs0qRvpcTduoHfjEnEUT/GWl98gQU67AbUlXOGkIL6ypw6nhbkYCfvszY+wVV3O4sMfN/o6gKfGAjxKOe0DiXUUjsFoWRYmnuRIe4NLpcXw=
