name: Open Mentoring
markdown: redcarpet
pygments: true
permalink: /:categories/:title.html
languages: &languages
  - name: 'English'
    value: 'en'
  - name: 'Español'
    value: 'es'
  - name: 'Français'
    value: 'fr'
prose:
  siteurl: 'https://openmentoring.io'
  ignore:
    - .gitignore
    - .travis.yml
    - _config.yml
    - README.md
    - docs
    - CONTRIBUTING.md
    - LICENSE
    - INTENTIONS.md
    - MODEL.md
    - Makefile
    - '*/_topic'
  metadata:
    topics:
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          placeholder: "English"
          options: *languages
          selected: "en"
      - name: "slug"
        field:
          element: "hidden"
          label: "Slug"
          value: ''
      - name: "layout"
        field:
          element: "hidden"
          value: ''
      - name: "module"
        field:
          element: "hidden"
          value: ''
      - name: "title"
        field:
          element: "text"
          label: "Sections title"
          placeholder: "This is a title"
